/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ClimbingProvidedAnswers;
import org.openapitools.client.model.ClimbingQuestionnaire;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClimbingQuestion
 */
public class ClimbingQuestionTest {
    private final ClimbingQuestion model = new ClimbingQuestion();

    /**
     * Model tests for ClimbingQuestion
     */
    @Test
    public void testClimbingQuestion() {
        // TODO: test ClimbingQuestion
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'question'
     */
    @Test
    public void questionTest() {
        // TODO: test question
    }

    /**
     * Test the property 'questionnaire'
     */
    @Test
    public void questionnaireTest() {
        // TODO: test questionnaire
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

}
