/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.ClimbingQuestion;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClimbingProvidedAnswers
 */
public class ClimbingProvidedAnswersTest {
    private final ClimbingProvidedAnswers model = new ClimbingProvidedAnswers();

    /**
     * Model tests for ClimbingProvidedAnswers
     */
    @Test
    public void testClimbingProvidedAnswers() {
        // TODO: test ClimbingProvidedAnswers
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'answer'
     */
    @Test
    public void answerTest() {
        // TODO: test answer
    }

    /**
     * Test the property 'question'
     */
    @Test
    public void questionTest() {
        // TODO: test question
    }

}
