/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ClimbingQuestionnaire;
import org.openapitools.client.model.ClimbingQuestionnaireAnalysis;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClimbingQuestionnaireUser
 */
public class ClimbingQuestionnaireUserTest {
    private final ClimbingQuestionnaireUser model = new ClimbingQuestionnaireUser();

    /**
     * Model tests for ClimbingQuestionnaireUser
     */
    @Test
    public void testClimbingQuestionnaireUser() {
        // TODO: test ClimbingQuestionnaireUser
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

    /**
     * Test the property 'questionnaires'
     */
    @Test
    public void questionnairesTest() {
        // TODO: test questionnaires
    }

    /**
     * Test the property 'analysis'
     */
    @Test
    public void analysisTest() {
        // TODO: test analysis
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

}
