/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.ClimbingQuestionnaire;
import org.openapitools.client.model.ClimbingQuestionnaireUser;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClimbingQuestionnaireAnalysis
 */
public class ClimbingQuestionnaireAnalysisTest {
    private final ClimbingQuestionnaireAnalysis model = new ClimbingQuestionnaireAnalysis();

    /**
     * Model tests for ClimbingQuestionnaireAnalysis
     */
    @Test
    public void testClimbingQuestionnaireAnalysis() {
        // TODO: test ClimbingQuestionnaireAnalysis
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'minValue'
     */
    @Test
    public void minValueTest() {
        // TODO: test minValue
    }

    /**
     * Test the property 'maxValue'
     */
    @Test
    public void maxValueTest() {
        // TODO: test maxValue
    }

    /**
     * Test the property 'questionnaire'
     */
    @Test
    public void questionnaireTest() {
        // TODO: test questionnaire
    }

    /**
     * Test the property 'userResponse'
     */
    @Test
    public void userResponseTest() {
        // TODO: test userResponse
    }

}
