/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ClimbingQuestion;
import org.openapitools.client.model.ClimbingQuestionnaireAnalysis;
import org.openapitools.client.model.ClimbingQuestionnaireUser;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClimbingQuestionnaire
 */
public class ClimbingQuestionnaireTest {
    private final ClimbingQuestionnaire model = new ClimbingQuestionnaire();

    /**
     * Model tests for ClimbingQuestionnaire
     */
    @Test
    public void testClimbingQuestionnaire() {
        // TODO: test ClimbingQuestionnaire
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'accessRequired'
     */
    @Test
    public void accessRequiredTest() {
        // TODO: test accessRequired
    }

    /**
     * Test the property 'climbingQuestion'
     */
    @Test
    public void climbingQuestionTest() {
        // TODO: test climbingQuestion
    }

    /**
     * Test the property 'analysis'
     */
    @Test
    public void analysisTest() {
        // TODO: test analysis
    }

    /**
     * Test the property 'userResponses'
     */
    @Test
    public void userResponsesTest() {
        // TODO: test userResponses
    }

}
