/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.ClimbingQuestionnaire;
import org.openapitools.client.model.ClimbingQuestionnaireUser;

/**
 * ClimbingQuestionnaireAnalysis
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-12T19:52:35.504818235+02:00[Europe/Paris]")
public class ClimbingQuestionnaireAnalysis {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_MIN_VALUE = "minValue";
  @SerializedName(SERIALIZED_NAME_MIN_VALUE)
  private BigDecimal minValue;

  public static final String SERIALIZED_NAME_MAX_VALUE = "maxValue";
  @SerializedName(SERIALIZED_NAME_MAX_VALUE)
  private BigDecimal maxValue;

  public static final String SERIALIZED_NAME_QUESTIONNAIRE = "questionnaire";
  @SerializedName(SERIALIZED_NAME_QUESTIONNAIRE)
  private ClimbingQuestionnaire questionnaire;

  public static final String SERIALIZED_NAME_USER_RESPONSE = "userResponse";
  @SerializedName(SERIALIZED_NAME_USER_RESPONSE)
  private ClimbingQuestionnaireUser userResponse;


  public ClimbingQuestionnaireAnalysis id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public ClimbingQuestionnaireAnalysis message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(required = true, value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ClimbingQuestionnaireAnalysis minValue(BigDecimal minValue) {
    
    this.minValue = minValue;
    return this;
  }

   /**
   * Get minValue
   * @return minValue
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getMinValue() {
    return minValue;
  }


  public void setMinValue(BigDecimal minValue) {
    this.minValue = minValue;
  }


  public ClimbingQuestionnaireAnalysis maxValue(BigDecimal maxValue) {
    
    this.maxValue = maxValue;
    return this;
  }

   /**
   * Get maxValue
   * @return maxValue
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getMaxValue() {
    return maxValue;
  }


  public void setMaxValue(BigDecimal maxValue) {
    this.maxValue = maxValue;
  }


  public ClimbingQuestionnaireAnalysis questionnaire(ClimbingQuestionnaire questionnaire) {
    
    this.questionnaire = questionnaire;
    return this;
  }

   /**
   * Get questionnaire
   * @return questionnaire
  **/
  @ApiModelProperty(required = true, value = "")

  public ClimbingQuestionnaire getQuestionnaire() {
    return questionnaire;
  }


  public void setQuestionnaire(ClimbingQuestionnaire questionnaire) {
    this.questionnaire = questionnaire;
  }


  public ClimbingQuestionnaireAnalysis userResponse(ClimbingQuestionnaireUser userResponse) {
    
    this.userResponse = userResponse;
    return this;
  }

   /**
   * Get userResponse
   * @return userResponse
  **/
  @ApiModelProperty(required = true, value = "")

  public ClimbingQuestionnaireUser getUserResponse() {
    return userResponse;
  }


  public void setUserResponse(ClimbingQuestionnaireUser userResponse) {
    this.userResponse = userResponse;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClimbingQuestionnaireAnalysis climbingQuestionnaireAnalysis = (ClimbingQuestionnaireAnalysis) o;
    return Objects.equals(this.id, climbingQuestionnaireAnalysis.id) &&
        Objects.equals(this.message, climbingQuestionnaireAnalysis.message) &&
        Objects.equals(this.minValue, climbingQuestionnaireAnalysis.minValue) &&
        Objects.equals(this.maxValue, climbingQuestionnaireAnalysis.maxValue) &&
        Objects.equals(this.questionnaire, climbingQuestionnaireAnalysis.questionnaire) &&
        Objects.equals(this.userResponse, climbingQuestionnaireAnalysis.userResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, message, minValue, maxValue, questionnaire, userResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClimbingQuestionnaireAnalysis {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    minValue: ").append(toIndentedString(minValue)).append("\n");
    sb.append("    maxValue: ").append(toIndentedString(maxValue)).append("\n");
    sb.append("    questionnaire: ").append(toIndentedString(questionnaire)).append("\n");
    sb.append("    userResponse: ").append(toIndentedString(userResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

