/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ClimbingProvidedAnswers;
import org.openapitools.client.model.ClimbingQuestionnaire;

/**
 * ClimbingQuestion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-12T19:52:35.504818235+02:00[Europe/Paris]")
public class ClimbingQuestion {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  private String slug;

  public static final String SERIALIZED_NAME_QUESTION = "question";
  @SerializedName(SERIALIZED_NAME_QUESTION)
  private String question;

  public static final String SERIALIZED_NAME_QUESTIONNAIRE = "questionnaire";
  @SerializedName(SERIALIZED_NAME_QUESTIONNAIRE)
  private ClimbingQuestionnaire questionnaire;

  public static final String SERIALIZED_NAME_ANSWERS = "answers";
  @SerializedName(SERIALIZED_NAME_ANSWERS)
  private List<ClimbingProvidedAnswers> answers = new ArrayList<ClimbingProvidedAnswers>();


  public ClimbingQuestion id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public ClimbingQuestion slug(String slug) {
    
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSlug() {
    return slug;
  }


  public void setSlug(String slug) {
    this.slug = slug;
  }


  public ClimbingQuestion question(String question) {
    
    this.question = question;
    return this;
  }

   /**
   * Get question
   * @return question
  **/
  @ApiModelProperty(required = true, value = "")

  public String getQuestion() {
    return question;
  }


  public void setQuestion(String question) {
    this.question = question;
  }


  public ClimbingQuestion questionnaire(ClimbingQuestionnaire questionnaire) {
    
    this.questionnaire = questionnaire;
    return this;
  }

   /**
   * Get questionnaire
   * @return questionnaire
  **/
  @ApiModelProperty(required = true, value = "")

  public ClimbingQuestionnaire getQuestionnaire() {
    return questionnaire;
  }


  public void setQuestionnaire(ClimbingQuestionnaire questionnaire) {
    this.questionnaire = questionnaire;
  }


  public ClimbingQuestion answers(List<ClimbingProvidedAnswers> answers) {
    
    this.answers = answers;
    return this;
  }

  public ClimbingQuestion addAnswersItem(ClimbingProvidedAnswers answersItem) {
    this.answers.add(answersItem);
    return this;
  }

   /**
   * Get answers
   * @return answers
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ClimbingProvidedAnswers> getAnswers() {
    return answers;
  }


  public void setAnswers(List<ClimbingProvidedAnswers> answers) {
    this.answers = answers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClimbingQuestion climbingQuestion = (ClimbingQuestion) o;
    return Objects.equals(this.id, climbingQuestion.id) &&
        Objects.equals(this.slug, climbingQuestion.slug) &&
        Objects.equals(this.question, climbingQuestion.question) &&
        Objects.equals(this.questionnaire, climbingQuestion.questionnaire) &&
        Objects.equals(this.answers, climbingQuestion.answers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slug, question, questionnaire, answers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClimbingQuestion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    questionnaire: ").append(toIndentedString(questionnaire)).append("\n");
    sb.append("    answers: ").append(toIndentedString(answers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

