/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.ClimbingQuestionnaire;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClimbingQuestionnaireApi
 */
@Ignore
public class ClimbingQuestionnaireApiTest {

    private final ClimbingQuestionnaireApi api = new ClimbingQuestionnaireApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void climbingQuestionnaireControllerFindAllTest() throws ApiException {
        String withQuestions = null;
        List<ClimbingQuestionnaire> response = api.climbingQuestionnaireControllerFindAll(withQuestions);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void climbingQuestionnaireControllerFindForUserTest() throws ApiException {
        String authorization = null;
        List<ClimbingQuestionnaire> response = api.climbingQuestionnaireControllerFindForUser(authorization);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void climbingQuestionnaireControllerFindOneTest() throws ApiException {
        String id = null;
        String withQuestions = null;
        ClimbingQuestionnaire response = api.climbingQuestionnaireControllerFindOne(id, withQuestions);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void climbingQuestionnaireControllerGetAnalysisMessageTest() throws ApiException {
        BigDecimal questionnaire = null;
        api.climbingQuestionnaireControllerGetAnalysisMessage(questionnaire);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void climbingQuestionnaireControllerSaveUserQuestionnaireTest() throws ApiException {
        String authorization = null;
        api.climbingQuestionnaireControllerSaveUserQuestionnaire(authorization);

        // TODO: test validations
    }
    
}
