/*
 * Codealpine
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateNavlinkDto;
import org.openapitools.client.model.UpdateNavlinkDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NavigationLinksApi
 */
@Ignore
public class NavigationLinksApiTest {

    private final NavigationLinksApi api = new NavigationLinksApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void navlinksControllerV1CreateTest() throws ApiException {
        CreateNavlinkDto createNavlinkDto = null;
        api.navlinksControllerV1Create(createNavlinkDto);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void navlinksControllerV1FindAllTest() throws ApiException {
        api.navlinksControllerV1FindAll();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void navlinksControllerV1FindOneTest() throws ApiException {
        String id = null;
        api.navlinksControllerV1FindOne(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void navlinksControllerV1RemoveTest() throws ApiException {
        String id = null;
        api.navlinksControllerV1Remove(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void navlinksControllerV1UpdateTest() throws ApiException {
        String id = null;
        UpdateNavlinkDto updateNavlinkDto = null;
        api.navlinksControllerV1Update(id, updateNavlinkDto);

        // TODO: test validations
    }
    
}
